<<<<<<< HEAD
# Generated by Django 5.1.7 on 2025-10-14 22:01
=======
# Generated by Django 5.1.5 on 2025-09-30 00:00
>>>>>>> a60596feb95b2115a9835361dd107b169b114ab5

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        ('leads', '0001_initial'),
        ('propiedades', '0001_initial'),
=======
        ('leads', '0006_contacto_owner_evento_owner'),
        ('propiedades', '0003_propiedad_owner'),
>>>>>>> a60596feb95b2115a9835361dd107b169b114ab5
    ]

    operations = [
        migrations.CreateModel(
            name='Aviso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('completado', 'Completado'), ('atrasado', 'Atrasado')], default='pendiente', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
<<<<<<< HEAD
                ('evento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aviso', to='leads.evento')),
=======
>>>>>>> a60596feb95b2115a9835361dd107b169b114ab5
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.contacto')),
                ('propiedad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='propiedades.propiedad')),
            ],
        ),
    ]
