# Generated by Django 5.1.7 on 2025-10-16 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avisos', '0001_initial'),
        ('leads', '0009_alter_contacto_telefono_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aviso',
            name='evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aviso', to='leads.evento'),
        ),
    ]
