# Generated by Django 5.1.5 on 2025-10-13 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avisos', '0001_initial'),
        ('leads', '0008_contacto_last_contact_at_contacto_next_contact_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aviso',
            name='evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aviso', to='leads.evento'),
        ),
    ]
