# Generated by Django 5.1.7 on 2025-10-16 22:18

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('ubicacion', models.CharField(max_length=255)),
                ('tipo_de_propiedad', models.CharField(choices=[('casa', 'Casa'), ('departamento', 'Departamento'), ('hotel', 'Hotel')], default='casa', max_length=50)),
                ('disponibilidad', models.CharField(max_length=50)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('moneda', models.CharField(choices=[('USD', 'USD'), ('ARS', 'ARS')], default='USD', max_length=10)),
                ('ambiente', models.PositiveIntegerField(default=1)),
                ('antiguedad', models.PositiveIntegerField(default=0)),
                ('banos', models.PositiveIntegerField(default=1)),
                ('superficie', models.DecimalField(decimal_places=2, help_text='Superficie en m²', max_digits=10)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('vendido', 'Vendido'), ('reservado', 'Reservado')], default='disponible', max_length=20)),
                ('vendida_en', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='propiedades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_alta'],
            },
        ),
        migrations.CreateModel(
            name='PropiedadImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='propiedades/')),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='propiedades.propiedad')),
            ],
        ),
        migrations.AddIndex(
            model_name='propiedad',
            index=models.Index(fields=['tipo_de_propiedad'], name='propiedades_tipo_de_cddc2c_idx'),
        ),
        migrations.AddIndex(
            model_name='propiedad',
            index=models.Index(fields=['estado'], name='propiedades_estado_79f814_idx'),
        ),
        migrations.AddIndex(
            model_name='propiedad',
            index=models.Index(fields=['disponibilidad'], name='propiedades_disponi_c40c10_idx'),
        ),
        migrations.AddIndex(
            model_name='propiedad',
            index=models.Index(fields=['moneda', 'precio'], name='propiedades_moneda_439827_idx'),
        ),
        migrations.AddIndex(
            model_name='propiedad',
            index=models.Index(fields=['vendida_en'], name='propiedades_vendida_6fe877_idx'),
        ),
    ]
