<<<<<<< HEAD:backend/propiedades/migrations/0002_alter_propiedad_disponibilidad.py
# Generated by Django 5.1.7 on 2025-09-24 22:27
=======
# Generated by Django 5.1.7 on 2025-09-23 23:37
>>>>>>> 0e749bfef4f8f82e588fc854695ddf450b2ba9be:backend/propiedades/migrations/0002_alter_propiedad_banos.py

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad',
            name='disponibilidad',
            field=models.CharField(choices=[('alquiler', 'Alquiler'), ('venta', 'Venta'), ('temporal', 'Temporal')], default='venta', max_length=50),
        ),
    ]
