# Generated by Django 5.1.7 on 2025-10-13 21:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='propiedades', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='vendida_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='disponibilidad',
            field=models.CharField(choices=[('venta', 'Venta'), ('alquiler', 'Alquiler'), ('alquiler_temporario', 'Alquiler Temporario')], default='venta', max_length=50),
        ),
        migrations.AddIndex(
            model_name='propiedad',
            index=models.Index(fields=['vendida_en'], name='propiedades_vendida_6fe877_idx'),
        ),
    ]
