# Generated by Django 5.1.7 on 2025-09-23 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad',
            name='banos',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
