# Generated by Django 5.1.7 on 2025-09-24 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad',
            name='disponibilidad',
            field=models.CharField(choices=[('alquiler', 'Alquiler'), ('venta', 'Venta'), ('temporal', 'Temporal')], default='venta', max_length=50),
        ),
    ]
