# Generated by Django 5.1.7 on 2025-10-28 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0002_alter_propiedad_tipo_de_propiedad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propiedadimagen',
            options={'ordering': ['propiedad', 'id'], 'verbose_name': 'Imagen de Propiedad', 'verbose_name_plural': 'Imágenes de Propiedades'},
        ),
        migrations.AlterField(
            model_name='propiedadimagen',
            name='imagen',
            field=models.ImageField(help_text='Imagen de la propiedad', upload_to='propiedades_multiples/'),
        ),
    ]
