# Generated by Django 5.1.5 on 2025-09-30 00:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0003_propiedad_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='vendida_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='propiedad',
            index=models.Index(fields=['vendida_en'], name='propiedades_vendida_6fe877_idx'),
        ),
    ]
