# Generated by Django 5.1.7 on 2025-10-14 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0004_propiedad_vendida_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad',
            name='tipo_de_propiedad',
            field=models.CharField(choices=[('casa', 'Casa'), ('departamento', 'Departamento'), ('ph', 'Ph'), ('terreno', 'Terreno'), ('cochera', 'Cochera'), ('local', 'Local'), ('oficina', 'Oficina'), ('consultorio', 'Consultorio'), ('quinta', 'Quinta'), ('chacra', 'Chacra'), ('galpon', 'Galpon'), ('deposito', 'Deposito'), ('campo', 'Campo'), ('hotel', 'Hotel'), ('fondo de comercio', 'Fondo de Comercio'), ('edificio', 'Edificio'), ('otro', 'Otro')], default='casa', max_length=50),
        ),
    ]
