# Generated by Django 5.1.7 on 2025-10-16 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0005_alter_propiedad_tipo_de_propiedad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad',
            name='tipo_de_propiedad',
            field=models.CharField(choices=[('casa', 'Casa'), ('departamento', 'Departamento'), ('hotel', 'Hotel')], default='casa', max_length=50),
        ),
    ]
