# Generated by Django 5.1.7 on 2025-10-27 23:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password_hash', models.CharField(max_length=128)),
                ('token', models.CharField(editable=False, max_length=40, unique=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('telefono', models.CharField(blank=True, help_text='Solo números, sin espacios ni símbolos.', max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Solo se permiten números.', regex='^\\d+$')])),
                ('dni', models.CharField(blank=True, max_length=8, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\d{7,8}$', 'DNI inválido (7 u 8 dígitos).')])),
                ('reminder_every_days', models.PositiveSmallIntegerField(default=3, help_text='Cada cuántos días recordar al usuario hacer seguimiento (ej. 3, 5, 7).')),
            ],
        ),
    ]
