# Generated by Django 5.1.7 on 2025-10-13 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='reminder_every_days',
            field=models.PositiveSmallIntegerField(default=3, help_text='Cada cuántos días recordar al usuario hacer seguimiento (ej. 3, 5, 7).'),
        ),
    ]
