# Generated by Django 5.1.5 on 2025-09-30 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_dni_usuario_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='reminder_every_days',
            field=models.PositiveSmallIntegerField(default=3, help_text='Cada cuántos días recordar al usuario hacer seguimiento (ej. 3, 5, 7).'),
        ),
    ]
