# Generated by Django 5.1.7 on 2025-10-16 02:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_usuario_reminder_every_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='dni',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\d{7,8}$', 'DNI inválido (7 u 8 dígitos).')]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(blank=True, help_text='Solo números, sin espacios ni símbolos.', max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Solo se permiten números.', regex='^\\d+$')]),
        ),
    ]
