# Generated by Django 5.1.5 on 2025-09-24 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_add_evento'),
        ('leads', '0003_seed_estados'),
    ]

    operations = [
    ]
