# Generated by Django 5.1.5 on 2025-09-30 00:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_contacto_owner_evento_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
