# Generated by Django 5.1.5 on 2025-09-30 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_contacto_creado_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='last_contact_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contacto',
            name='next_contact_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contacto',
            name='next_contact_note',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
