# Generated by Django 5.1.7 on 2025-10-11 03:31

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0008_contacto_last_contact_at_contacto_next_contact_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='telefono',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Solo dígitos, sin + ni guiones', max_length=15, validators=[django.core.validators.RegexValidator(message='Ingrese solo dígitos.', regex='^\\d{1,15}$')]),
        ),
        migrations.AddIndex(
            model_name='contacto',
            index=models.Index(fields=['next_contact_at'], name='leads_conta_next_co_5f329e_idx'),
        ),
        migrations.AddIndex(
            model_name='contacto',
            index=models.Index(fields=['last_contact_at'], name='leads_conta_last_co_42add6_idx'),
        ),
        migrations.AddIndex(
            model_name='contacto',
            index=models.Index(fields=['creado_en'], name='leads_conta_creado__7cac9d_idx'),
        ),
    ]
