# Generated by Django 5.1.7 on 2025-10-16 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0009_alter_contacto_telefono_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='contacto',
            name='leads_conta_next_co_5f329e_idx',
        ),
        migrations.RemoveIndex(
            model_name='contacto',
            name='leads_conta_last_co_42add6_idx',
        ),
        migrations.RemoveIndex(
            model_name='contacto',
            name='leads_conta_creado__7cac9d_idx',
        ),
        migrations.AlterField(
            model_name='contacto',
            name='telefono',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
